# Generated by Django 2.1.7 on 2019-03-31 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupersons',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 3, 31, 8, 32, 51, 791668, tzinfo=utc)),
        ),
    ]
