# Generated by Django 2.1.7 on 2019-03-31 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0002_auto_20190331_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupersons',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 3, 31, 8, 33, 31, 442782, tzinfo=utc)),
        ),
    ]
