# Generated by Django 2.1.7 on 2019-03-31 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0005_auto_20190331_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupersons',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 3, 31, 9, 3, 19, 625419, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='mybook',
            table='书籍',
        ),
    ]
