# Generated by Django 2.1.7 on 2019-03-31 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0006_auto_20190331_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybook',
            options={'ordering': ['-pubdate', '-read_num']},
        ),
        migrations.AddField(
            model_name='mybook',
            name='read_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='groupersons',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 3, 31, 9, 9, 21, 2511, tzinfo=utc)),
        ),
    ]
