"""添加年龄

Revision ID: 15e814365b01
Revises: bc15c10ae693
Create Date: 2019-03-10 13:52:39.572735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e814365b01'
down_revision = 'bc15c10ae693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('\u7f51\u7ad9\u7528\u6237', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('网站用户', 'age')
    # ### end Alembic commands ###
