"""empty message

Revision ID: 0f1bd320ac33
Revises: 90f98f2266a7
Create Date: 2019-03-29 14:23:55.880140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1bd320ac33'
down_revision = '90f98f2266a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('comment_num', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('play_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'play_num')
    op.drop_column('movie', 'comment_num')
    # ### end Alembic commands ###
