"""empty message

Revision ID: 722db5e5dba2
Revises: a1613521bc2f
Create Date: 2019-03-29 10:17:27.419463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722db5e5dba2'
down_revision = 'a1613521bc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_content', table_name='comment')
    op.create_index(op.f('ix_comment_content'), 'comment', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_content'), table_name='comment')
    op.create_index('ix_comment_content', 'comment', ['content'], unique=True)
    # ### end Alembic commands ###
