"""empty message

Revision ID: 76ef35536e41
Revises: 722db5e5dba2
Create Date: 2019-03-29 13:56:25.548740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ef35536e41'
down_revision = '722db5e5dba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'movie', ['url'], unique=True)
    # ### end Alembic commands ###
