"""empty message

Revision ID: 90f98f2266a7
Revises: 72042cc52eb8
Create Date: 2019-03-29 13:57:15.105278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f98f2266a7'
down_revision = '72042cc52eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movie_name', table_name='movie')
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.create_index('ix_movie_name', 'movie', ['name'], unique=True)
    # ### end Alembic commands ###
