"""empty message

Revision ID: 5cd4427da8b7
Revises: 70051403c3d3
Create Date: 2019-03-30 11:15:21.574712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd4427da8b7'
down_revision = '70051403c3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'release_time')
    # ### end Alembic commands ###
