"""empty message

Revision ID: 70051403c3d3
Revises: 0ba7883aa527
Create Date: 2019-03-30 11:15:13.857832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70051403c3d3'
down_revision = '0ba7883aa527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'release_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
